### ISSUE TITLE
MCP2515 or SN65HVD230

### ISSUE THREAD

**Issue by AndrasSzep** [AK-Homberger/M5Stack-NMEA-2000-Display-CAN-BUS#1]
When I replace the https://www.waveshare.com/sn65hvd230-can-board.htm with the small ones https://www.aliexpress.com/item/32686386479.html?spm=a2g0s.9042311.0.0.57e44c4duiCaZT
 there is no signal on M5Stack. Same breakout boards work clueless on other ESP32 modules (https://diyprojects.io/wemos-lolin32-lite-compact-revision-lolin32-4-90/).

Any idea what could be to cause?

**Comment by AK-Homberger** [comment]
Unortunately, I have no idea.

**Comment by AndrasSzep** [comment]
Thanks anyway, and **special thanks for your development**.  It is the core for a half a dozen of gadgets I made.
:–)

**Comment by drjz** [comment]
Interesting. I also tried the M5Stack CAN interface https://docs.m5stack.com/en/module/commu no CAN Data are received. Also same with https://docs.m5stack.com/en/unit/can.
Any ideas?

**Comment by AK-Homberger** [comment]
I don't own that device. Therefore I can't test.

**Comment by AK-Homberger** [comment]
Closed
